### ISSUE TITLE
Add dependency audits to ci

### ISSUE THREAD

**Issue by rillian** [brave-experiments/star-randsrv#11]
It would be good to run some kind of dependency audit on the codebase as part of the github actions. We can invoke `cargo audit` for the rust code. Is there an equivalent for the go side?

**Comment by rillian** [comment]
`make lint` already invokes `cargo audit` so maybe I'm just asking if there's a similar command for go.

**Comment by NullHypothesis** [comment]
Go itself currently does not provide that but we have GitHub's [Dependabot](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-supply-chain-security#what-is-dependabot) enabled, which is going to notify us once a dependency has a security issue. This should suffice for now.
